# site settings

title: Vox Fidelium
description: A Call to all Faithful Catholics to raise their voices to proclaim our belief in the infallible teachings of the Church.
taglong: A Call to all Faithful Catholics
tagshort: Jekyll theme
url: /
baseurl: ""
permalink: pretty
repo: https://github.com/username/username.github.io

# author settings

author:
  name: 
  email: 
photo: 

# social media links

social:

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
